### ISSUE TITLE
Getting high on Nuka Cola?

### ISSUE THREAD

**Issue by Goldrobo** [DesertRose2/desertrose#101]
## Round ID: 2832
Nuka cola, for some reason, emits lights and other effects as if the person took space drugs.

## Reproduction:

Drank an ordinary bottle of Nuka cola, proceeded to see lights.  This is not normal.

**Comment by Goldrobo** [comment]
Ok I don't know why the description won't show, but basically Nuka Cola has effects like space drugs, and it shouldn't.

**Comment by nokele** [comment]
Not entirely sure why that was here, but I commented out
//M.set_drugginess(30)
//M.dizziness +=1.5
so should be fixed now.
