### ISSUE TITLE
nyctophobia and speed glitch/bug up and down!

### ISSUE THREAD

**Issue by R9b1t** [DesertRose2/desertrose#105]
## Reproduction:

I'd have to go back about it. I chose Nyctophobia, Phobia, Quick Step, Musician as my quirks. i walked into the mines as bos and it negated my nycto-whatever. then was able to super-run.

Yeah so basically quick step and nycto. walk into darkness. youll slow down. turn on a flashlight and the thing stops affecting you. just about cap max speed without sprinting. pretty based imo

![sp buffer](https://user-images.githubusercontent.com/80088607/110074611-b9962000-7d3e-11eb-9002-065493738bc5.png)

(ALSO WALKING INTO A DARK SPOT WITH NYCTOPHOBIA WILL NEGATE YOUR SPRINT ENTIRELY ASSUMING YOU DONT HAVE THE QUICK STEP PERK, then quick step will take into effect and basically max out your speed. based, totally not something i could abuse as a nightvision prepping brotherhood of steel knight with a stunprod)

**Comment by MarinaGryphon** [comment]
basically, quick step is bugged and is probably going to get removed until it can be fixed properly.

**Comment by nokele** [comment]
quickstep was removed, close this
