### ISSUE TITLE
Ammo/Magazines missing from Reloading bench 

### ISSUE THREAD

**Issue by Seabass390** [DesertRose2/desertrose#107]
## Reproduction:
There are no options for certain calibers and magazines to print within the reloading benches. These are (to my best knowledge) - 

Calibers:
9mm FMJ - /obj/item/projectile/bullet/c9mm
9mm AP - /obj/item/projectile/bullet/c9mm/ap
9mm JHP - /obj/item/projectile/bullet/c9mm/jhp
9mm +P - /obj/item/projectile/bullet/c9mm/op
12.7mm FMJ - /obj/item/projectile/bullet/a127mm
12.7mm JHP - /obj/item/projectile/bullet/a127mm/jhp
.22lr - /obj/item/projectile/bullet/c22
.38 Special - /obj/item/projectile/bullet/c38
.357 JFP bullet - /obj/item/projectile/bullet/a357/jfp
44 SWC bullet - /obj/item/projectile/bullet/m44/swc
.45-70 SWC bullet - /obj/item/projectile/bullet/c4570/swc
7.62 JSP bullet - /obj/item/projectile/bullet/a762/jsp
7.62 match bullet - /obj/item/projectile/bullet/a762/match
5.56 match bullet - /obj/item/projectile/bullet/a556/match
.45 FMJ - /obj/item/projectile/bullet/c45
.45 JHP - /obj/item/projectile/bullet/c45/jhp
.45 +P - /obj/item/projectile/bullet/c45/op

Magazines:
Small rifle magazine (5.56mm) - /obj/item/ammo_box/magazine/m556/rifle/small
Extended rifle magazine (5.56mm) - /obj/item/ammo_box/magazine/m556/rifle/extended
Rifle magazine (7.62x51) - /obj/item/ammo_box/magazine/m762
Extended rifle magazine (7.62x51) - /obj/item/ammo_box/magazine/m762/ext
Sniper rifle magazine (7.62x51) - ??? (Cannot find, missing from the database, although still spawned in through loadouts)
Toploader magazine (10mm) - /obj/item/ammo_box/magazine/m10mm_p90
Toploader magazine (.22lr) - /obj/item/ammo_box/magazine/m22smg

This list is by no means exhaustive. There may have been things I missed, but these are what I could find with a good hour of cross-referencing and scrutinizing.

	
To recreate: simply go in-game and check the reloading benches and cross-reference this list, and you'll find most, if not all, of these items missing.

**Comment by Superballs69** [comment]
.38 will probably be shelved for now, everything else will be fixed.
