### ISSUE TITLE
Centurion Setup

### ISSUE THREAD

**Issue by TheGodArtivus** [DesertRose2/desertrose#144]
I don't think I need all that writing from before. The Centurion setup misses a gas tank of sort like a plasma tank for his Goliath on spawn, please maybe look into getting one for it, thanks.

**Comment by Pebblesthe2nd** [comment]
Found a solution for it, basically something with the /powerfist family, so I just sidestepped it by shortening the path.
If you want to solve it some other way go for it, otherwise its part of the centurion focused PR Im almost done with, not a huge thing this time.

**Comment by Pebblesthe2nd** [comment]
The goliath still feels off somehow, not sure. Using it on a wall its the same as a spatha, on mobs it seems worse. I don't quite get whats wrong, might need some sort of tweak.
