### ISSUE TITLE
R84 LMG 5,56 AMMOBOX can't be crafted

### ISSUE THREAD

**Issue by hawkwest** [DesertRose2/desertrose#147]

**Comment by Seabass390** [comment]
I wanted to add to this issue, instead of making a new one.

There are also more magazines missing, such as...

/obj/item/ammo_box/magazine/m45
	name = "handgun magazine (.45)"
	
/obj/item/ammo_box/magazine/tommygunm45
	name = "drum magazine (.45)"

/obj/item/ammo_box/magazine/garand308
	name = "en-bloc clip (7.62x51mm)"

**Comment by Seabass390** [comment]
/obj/item/ammo_box/a357
	name = "speed loader (.357)"
	
/obj/item/ammo_box/a762
	name = "stripper clip (7.62mm)"
	
/obj/item/ammo_box/shotgun
	name = "stripper clip (shotgun shells)"
	
/obj/item/ammo_box/a762/doublestacked
	name = "double stack stripper clip (.308)"

These are fluff, but might be good to add them as well, incase we need to use them in one form or another.
