### ISSUE TITLE
Rebase CIT Blacksmithing Skill levelling + Better Anvil issue

### ISSUE THREAD

**Issue by hawkwest** [DesertRose2/desertrose#161]
## Reproduction: A round earlier I hard levelled my skill of Blacksmithing https://i.gyazo.com/c55e108b0e2d85a4f26f535ed0604e72.png up to like 900xp (I forgot the exact number), but turns out it resets each time, so all the work was for nothing. It'd be nice if these skills were to save, so one could RP as a Master Weaponforger. 

There's also the case of the not being able to make better anvils ( the basic anvil can only be 'bought' on CIT, while Basalt Anvil can't be made without a Lavaland.. which doesn't exist on the server)

**Comment by nokele** [comment]
ye this will likely be reworked in the future.
