### ISSUE TITLE
Rangers are unable to Disarm due to Ranger Takedown CQC

### ISSUE THREAD

**Issue by BurpleBineapple** [DesertRose2/desertrose#163]
## Issue
Due to the way CQC works, the Ranger Takedown CQC replaces the disarm move on standing opponents. Rangers are unable to disarm someone without first drop kicking them.

## Reproduction:
>Join as Ranger
>Get into melee range of someone
>Switch to disarm intent and left click in an effort to disarm their weapon
>Writhe in agony because this only knocked them down any they can still fire their weapon at  you

## Suggestions

An easier fix would be to change the Ranger Takedown to be a right click action when in combat mode to replace pushing. Full CQC has other moves that do in fact disarm you when using a takedown.

Another fix would be making the Ranger Takedown also disarm people when used.

**Comment by prawn04** [comment]
I think having an instant disarm and knockdown might be a bit too powerful. Maybe make it like CQC where you need to hit two moves prior to it activating. Disarm Grab, maybe?
