### ISSUE TITLE
Caps/Aurei same item

### ISSUE THREAD

**Issue by Honto335** [DesertRose2/desertrose#166]

**Comment by cornercube** [comment]
similar problem encountered with NCR dollars and caps, Dollars seemed to merge with the caps when they enter the same conttainer

**Comment by Covert0ddity** [comment]
Dollars, Denarii, Aurei, and Caps are all technically the same item at the moment and all worth the same. I will attempt to fix this soon.

**Comment by Covert0ddity** [comment]
Fixed.
