### ISSUE TITLE
Energy Ammo un-craftable outside of protolathe

### ISSUE THREAD

**Issue by ThatReformedEngineer** [DesertRose2/desertrose#233]
In the title, any energy ammos for laser/plasma guns can not be crafted, even after reading the guns and bullets books, looking at the reloading bench, or just checking the ammunition crafting tab. Was likely accidentally not ported over.

**Comment by K0NFL1QT** [comment]
I think this is intended.

**Comment by ThatReformedEngineer** [comment]
Is it, do you know who said this?

**Comment by Covert0ddity** [comment]
That is not intended, just wasn't ported over. Will fix when I can.
