### ISSUE TITLE
Putting Silencer on weapons makes the sprite disappear

### ISSUE THREAD

**Issue by hawkwest** [DesertRose2/desertrose#239]

**Comment by hawkwest** [comment]
And same with Marksman.. Pretty sure Silencer just.. makes all the gun sprites disappear..

**Comment by The-Bompton-Rat** [comment]
Tested this myself on accident. The sniper, assault carbine, and marksman rifle all lost their sprite when a silencer was put on.

**Comment by Superballs69** [comment]
These all should be fixed with PR #232 as they include new suppressor changes.
