### ISSUE TITLE
Melee Rework

### ISSUE THREAD

**Issue by saran7681** [DesertRose2/desertrose#278]
These are the changes I propose on having the melee weapon numbers changed.

Two-Handed weapons
Bumper Sword : 60 force/ 0.4 armor penetration/ Wound bonus unchanged/ passive 15% delimb chance and 15% stun for 0.5 seconds
Woodaxe : 55 Force/0.4 armor penetration / 30 Bare_Wound_Bonus and 0 wound_bonus/passive 15% delimb chance and 15% stun for 0.5 seconds 
Sledgehammer : 55 Force / 0.4 armor penetration / Wound bonus are to be unchanged / 15% stun for 1.25 seconds
War Mace : 50 Force / armor pen unchanged/ wound bonus are to be unchanged / 15% stun for 1.25 seconds
Baseball bat : 40 Force / no armor pen/ Bare_wound_bonus to 20/ 15% chance stun for 0.5 second
Spiked Baseball Bat : 45 Force/no armor pen/ Bare_wound_bonus/ 15% chance stun for 0.5 second
Super sledge : 65 Force/ 0.4 armor penetration/ 20 Bare_wound_Bonus & 20 Wound_Bonus/ 20% chance stun for 1.25 seconds
Thermic Lance : 65 Fire/0.4 armor penetration/ Should have some delimbing chance or just straight up burn limbs off with a chance of 20%

One handed weapons

Spatha : 45 Force/0.3 armor penetration/15% chance of delimb and 10% chance of knockdown/ Bare wound Bonus to 5 and Wound Bonus to 5
Gladius: 40 Force/0.3 armor penetration/ 20% chance of delimb and 10% chance of Knock down/Bare wound bonus to 5 and wound bonus to 5
Machete: 35 Force/0.3 armor penetration/15% chance of delimb and 10% chance of knock down/Bare wound bonus to 5 and wound bonus to 5
Reinforced Machete : 40 Force/0.3 armor penetration/15% chance of delimb and 10% chance of knock down/Bare wound bonus to 10 and wound bonus to 10
Trench Knife : Armor pentration to 0.2
Combat Knife : Unchanged
Survival Knife : Unchanged
Kitchen Knife : Unchanged 
Bowie Knife : Unchanged 
Ritual Dagger : Unchanged 
Frying Pan : Unchanged,but maybe give it a 10% block chance?
Ripper : 55 Force/0.4 armor penetration/ 15 chance of delimb and 10% chance of knock down/Wound Bonus to 10 and Bare wound bonus to 10
Energy Axe : 55 force/ 0.6 armor penetration/ 15 chance of delimb and 10% chance of knock down/ Wound bonus to 0 and bare wound bonus to 0
Shishkebab : 60 force/ 0.5 armor penetration/ no chance of delimbing but has 15% of knock down/ wound bonus to 0 and bare wound bonus to 0
Butchers cleaver : Unchanged 
Pipe : unchanged
War club : 40 force/ 0.4 armor penetration / No delimbing as it is a blunt weapon but has a 15 chance of knock down/ Bare wound bonus to 10 and wound bonus to 10

Unarmed Weapons

Won't be touched as of now. As power fists weapons need to be fixed,they are able to one shot people with gas canister set to level 3.

note : Delimbing and stun has to be coded into the weapons.

**Comment by Stalkeros2** [comment]
Buff PKC pls.

**Comment by saran7681** [comment]
> Buff PKC pls.

I have been told that PKC is not a fallout weapon,so it will be removed or so. Adding to the fact that it is a mining tool more then it is a weapon and it can be bought too cheap at a cost of 500 caps.
