### ISSUE TITLE
The defibrilators at the Follower clinic arent working for some reason.

### ISSUE THREAD

**Issue by Spartan2548** [DesertRose2/desertrose#302]

**Comment by Seabass390** [comment]
Personally tested on the most up-to-date code with no modifications. I took a defibrillator and used it on a corpse and it worked. Are you sure this isn't an error on your part? Was the defib charged? Was it held in both hands? Were you targeting the chest?

More detail will be needed for this issue. Unless it's confirmed a personal missight
