### ISSUE TITLE
Reloader bench eats screwdrivers

### ISSUE THREAD

**Issue by K0NFL1QT** [DesertRose2/desertrose#305]
## Description
Reloader deconstructs screwdrivers into metal, preventing you from opening and upgrading them.

## Reproduction:
Try to open a reloader with a screwdriver in currect round.

**Comment by nokele** [comment]
seems to work fine?

**Comment by K0NFL1QT** [comment]
Yeah, it only happened once, and even in the same round just 5 minutes later someone was able to unscrew it. But I definately lost a screwdriver and saw a metal reclamation message as the reloader ate it.
