### ISSUE TITLE
Mentats Recipe Uncraftable

### ISSUE THREAD

**Issue by Seabass390** [DesertRose2/desertrose#486]
## Reproduction:

/datum/chemical_reaction/mentats
	name = "mentats"
	id = /datum/reagent/medicine/mentat
	results = list(/datum/reagent/medicine/mentat = 3)
	required_reagents = list(/datum/reagent/medicine/mannitol = 1, /datum/reagent/acetone = 1, /datum/reagent/oxygen = 1, /datum/reagent/cellulose = 1)
	required_temp = 451
	
This recipe is inherently flawed. The first three ingredients: mannitol, acetone, and oxygen - create neurine. This makes the cellulose uncombinable, leading to just neurine and cellulose. 

A workaround would be to condense the first three ingredients to just Neurine. This would allow for the chemical to be craftable.

I.E -  required_reagents = list(/datum/reagent/medicine/neurine = 1, /datum/reagent/cellulose = 1)
	required_temp = 451

**Comment by panzer1944** [comment]
Fixing in my PR by replacing the first three with Neurine, since it's being made anyways lmao.
