### ISSUE TITLE
The YK42B Pulse Rifle does no damage to human targets

### ISSUE THREAD

**Issue by githubuser4141** [DesertRose2/desertrose#512]
## Reproduction:

Spawn/Find a YK42B Pulse Rifle, Spawn/Get a player-controlled human to fire at, fire at them, check their health. No damage.

The YK42B Pulse rifle (and it's carbine sub-type) doesn't cause any damage at all when shooting humans..  According to the code it's SUPPOSED to deal 28 damage at 75% AP, but also has a 'NODAMAGE' flag set, I'm no coder but perhaps this is causing issues?

**Comment by panzer1944** [comment]
lmao no clue when the no-dam flag was added to it, that's a bit of a bruh moment. I'll get around to fixing it alongside match and SWC
