### ISSUE TITLE
IEDs done did broke (Requires unobtainable soda cans, rather then bottles like oldbase)

### ISSUE THREAD

**Issue by HanSolo1519** [DesertRose2/desertrose#99]
## Round ID:

Unsure about the exact round ID, it was around noon 3/4/2021, a round later in the day is 2830

## Reproduction:

Legit just check the ied crafting recipe in ranged weapons, I tried ignoring it and using a glass soda bottle but it didn't work.

**Comment by nokele** [comment]
fixed.
